# Generated by Django 3.2.6 on 2021-08-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_charge_id',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
