# Generated by Django 3.2.6 on 2021-08-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210827_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=150)),
                ('massage', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
