# Generated by Django 3.2.6 on 2021-08-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contactmassage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmassage',
            name='readed',
            field=models.BooleanField(default=False),
        ),
    ]
