# Generated by Django 3.2.6 on 2021-08-27 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contactmassage_readed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMassage',
            new_name='ContactMessage',
        ),
    ]
