# Generated by Django 3.2.6 on 2021-08-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPagePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('BO', 'BEST OFFER'), ('FD', ''), ('LM', '')], max_length=200)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
