# Generated by Django 3.2.6 on 2021-08-29 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_landingpagepicture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LandingPagePicture',
            new_name='LandingPage',
        ),
    ]
