# Generated by Django 3.2.6 on 2021-08-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_landingpage_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('BO', 'BEST OFFER'), ('FD', 'FLASH DEALS'), ('LM', 'LAST MINUTE')], max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='LandingPage',
        ),
    ]
