# Generated by Django 3.2.6 on 2021-12-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20211019_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip',
            field=models.IntegerField(),
        ),
    ]
