# Generated by Django 3.2.6 on 2021-08-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=150)),
                ('massage', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('readed', models.BooleanField(default=False)),
            ],
        ),
    ]
