# Generated by Django 3.2.6 on 2021-08-28 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_account', '0005_auto_20210828_2231'),
        ('company', '0004_auto_20210828_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='social_media',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_account.socialmedia'),
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
    ]
