# Generated by Django 3.2.6 on 2021-08-28 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20210828_2219'),
        ('main_account', '0002_auto_20210828_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='social_media',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TeamMember', to='company.socialmedia'),
        ),
    ]
