# Generated by Django 3.2.6 on 2021-08-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_account', '0006_rename_socialmedia_socialmediaaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users_image'),
        ),
    ]
