# Generated by Django 3.2.6 on 2021-10-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_account', '0008_remove_socialmediaaccount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaaccount',
            name='name',
            field=models.CharField(default='default', max_length=150),
            preserve_default=False,
        ),
    ]
