name: WaiterNews Test

on: [push, pull_request]

jobs:

  test:
    name: Test Code
    runs-on: ${{ matrix.ubuntu }}
    strategy:
      matrix:
        python: ["3.8"]
        ubuntu: ["ubuntu-latest"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python }}'
      - name: Install Redis
        run: sudo apt-get install redis-server
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: coverage run ./WaiterShop/manage.py test core
      - name: Output Coverage
        run: coverage report && coverage xml

